version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - qr_storage:/app/qr
    restart: unless-stopped

volumes:
  qr_storage: